# base node image
FROM node:20-bullseye-slim as base

# Install openssl for Prisma
RUN apt-get update && apt-get install -y openssl git curl

# -----------------------------------------------------------------------------
# Stage 1. Install and build packages
# -----------------------------------------------------------------------------

FROM base as deps

USER node

WORKDIR /home/node/app

ARG FONT_AWESOME_TOKEN
ENV FONT_AWESOME_TOKEN=$FONT_AWESOME_TOKEN

# Copy the monorepo deps
COPY --chown=node:node package.json yarn.lock .npmrc turbo.json ./

# Copy packages
COPY --chown=node:node packages ./packages/

# Copy the web app
COPY --chown=node:node apps/web ./apps/web

# Install turbo
RUN yarn global add turbo

# Install packages
RUN yarn --production=false

RUN yarn build:web

# -----------------------------------------------------------------------------
# App
# -----------------------------------------------------------------------------

FROM base as app

USER node

WORKDIR /home/node/app

COPY --from=deps --chown=node:node /home/node/app/apps/web ./apps/web
COPY --from=deps --chown=node:node /home/node/app/packages ./packages
COPY --from=deps --chown=node:node /home/node/app/node_modules ./node_modules
COPY --from=deps --chown=node:node /home/node/app/package.json ./
COPY --from=deps --chown=node:node /home/node/app/yarn.lock ./
COPY --from=deps --chown=node:node /home/node/app/turbo.json ./

CMD ["yarn", "--cwd", "./apps/web", "start"]
