app = "web-metronome-sh"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
app = "yarn --cwd ./apps/web start"

[build]
dockerfile = "Dockerfile.web"

[deploy]
release_command = "yarn migrate:up"

[env]
NODE_ENV = "production"
PORT = "8080"
REDIS_QUEUE_URL = "top1.nearest.of.redis-metronome-sh.internal"
GITHUB_CLIENT_ID = "4326724a1503c54b6c3c"
WEB_URL = "https://next.metronome.sh"
PRIMARY_REGION = 'yyz'
TIMESCALEDB_HOST = "timescaledb-metronome-sh.flycast"
TIMESCALEDB_USER = "postgres"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 500
soft_limit = 450
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

# [services.ports.tls_options]
# alpn = ["h2"]

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 10
timeout = "2s"
