version: "3"
name: "metronome-dev"
services:
  db:
    platform: linux/amd64
    image: "timescale/timescaledb-ha:pg15.3-ts2.11.1"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "${DB_READ_USER}"
      POSTGRES_PASSWORD: "${DB_READ_PASSWORD}"
      POSTGRES_DB: "${DB_READ_DATABASE}"

    volumes:
      - "db:/home/postgres/pgdata/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_READ_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["-c", "max_connections=9999"]
    networks:
      - metronome-network

  redis:
    image: redis:6.2.6
    command:
      - redis-server
      - --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - metronome-network

networks:
  metronome-network:
    driver: bridge

volumes:
  db:
    driver: local
  redis:
    driver: local
